# Generated by Django 3.2.5 on 2021-08-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=128)),
                ('body', models.TextField()),
                ('img', models.ImageField(upload_to='media')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
